import { useState } from "react";

function Contact() {
  const [formData, setFormData] = useState({
      nom: "",
          email: "",
              message: "",
                });
                  const [erreurs, setErreurs] = useState({});
                    const [envoye, setEnvoye] = useState(false);

                      function handleChange(e) {
                          const { name, value } = e.target;
                              setFormData((prev) => ({ ...prev, [name]: value }));
                                }

                                  function valider() {
                                      const nouvellesErreurs = {};
                                          if (!formData.nom.trim()) {
                                                nouvellesErreurs.nom = "Le nom est requis.";
                                                    }
                                                        const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
                                                            if (!formData.email.trim()) {
                                                                  nouvellesErreurs.email = "L'adresse courriel est requise.";
                                                                      } else if (!emailRegex.test(formData.email.trim())) {
                                                                            nouvellesErreurs.email = "Adresse courriel invalide.";
                                                                                }
                                                                                    if (!formData.message.trim()) {
                                                                                          nouvellesErreurs.message = "Le message est requis.";
                                                                                              }
                                                                                                  return nouvellesErreurs;
                                                                                                    }

                                                                                                      async function handleSubmit(e) {
                                                                                                          e.preventDefault();
                                                                                                              const nouvellesErreurs = valider();
                                                                                                                  setErreurs(nouvellesErreurs);
                                                                                                                      if (Object.keys(nouvellesErreurs).length > 0) return;

                                                                                                                          try {
                                                                                                                                const res = await fetch("/api/contact", {
                                                                                                                                        method: "POST",
                                                                                                                                                headers: { "Content-Type": "application/json" },
                                                                                                                                                        body: JSON.stringify(formData),
                                                                                                                                                              });
                                                                                                                                                                    if (!res.ok) throw new Error("Échec de l'envoi");
                                                                                                                                                                          setEnvoye(true);
                                                                                                                                                                                setFormData({ nom: "", email: "", message: "" });
                                                                                                                                                                                    } catch (err) {
                                                                                                                                                                                          setErreurs({ envoi: "Impossible d'envoyer le message pour l'instant." });
                                                                                                                                                                                              }
                                                                                                                                                                                                }

                                                                                                                                                                                                  return (
                                                                                                                                                                                                      <section>
                                                                                                                                                                                                            <h1>Contact</h1>

                                                                                                                                                                                                                  {envoye && <p role="status">Merci ! Votre message a été envoyé.</p>}
                                                                                                                                                                                                                        {erreurs.envoi && <p role="alert">{erreurs.envoi}</p>}

                                                                                                                                                                                                                              <form onSubmit={handleSubmit} noValidate>
                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                <label htmlFor="nom">Nom</label>
                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                      id="nom"
                                                                                                                                                                                                                                                                                  name="nom"
                                                                                                                                                                                                                                                                                              type="text"
                                                                                                                                                                                                                                                                                                          value={formData.nom}
                                                                                                                                                                                                                                                                                                                      onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                  aria-invalid={erreurs.nom ? "true" : "false"}
                                                                                                                                                                                                                                                                                                                                              aria-describedby={erreurs.nom ? "erreur-nom" : undefined}
                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                  {erreurs.nom && <p id="erreur-nom">{erreurs.nom}</p>}
                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                            <label htmlFor="email">Courriel</label>
                                                                                                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                                                                                                  id="email"
                                                                                                                                                                                                                                                                                                                                                                                                                              name="email"
                                                                                                                                                                                                                                                                                                                                                                                                                                          type="email"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      value={formData.email}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              aria-invalid={erreurs.email ? "true" : "false"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          aria-describedby={erreurs.email ? "erreur-email" : undefined}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {erreurs.email && <p id="erreur-email">{erreurs.email}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label htmlFor="message">Message</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              id="message"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          name="message"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      value={formData.message}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              aria-invalid={erreurs.message ? "true" : "false"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          aria-describedby={erreurs.message ? "erreur-message" : undefined}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {erreurs.message && <p id="erreur-message">{erreurs.message}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button type="submit">Envoyer</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default Contact;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          